# Goal - to check whether the application code coverage doesn't have security threats/issues

name: Sonar Qube Scan

on:
    workflow_call:
      secrets:
        SONAR_TOKEN:
          required: true
        SONAR_HOST_URL:
          required: true

jobs:
    sonar-scanner:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
             
            - name: Verify Secret Presence
              run: |
                if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
                  echo "❌ ERROR: SONAR_TOKEN is empty!"
                  exit 1
                fi
                if [ -z "${{ secrets.SONAR_HOST_URL }}" ]; then
                  echo "❌ ERROR: SONAR_HOST_URL is empty!"
                  exit 1
                fi
                
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v5
              with:
                # pass custom project settings here
                args: >
                  -Dsonar.projectKey=devboard
              env:
                # 1. This environment variable tells SonarScanner exactly where your server lives
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
                # 2. This authenticates the connection
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
